project:
  type: website

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/BorjaRequena/BOUNCE/"
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]